// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateTodoReq struct {
	Title       string `json:"title"`
	Description string `json:"description,optional"`
}

type Todo struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type TodoListResp struct {
	List []Todo `json:"list"`
}

type TodoReq struct {
	ID int64 `path:"id"`
}

type UpdateTodoReq struct {
	ID          int64  `path:"id"`
	Title       string `json:"title,optional"`
	Description string `json:"description,optional"`
	Completed   bool   `json:"completed,optional"`
}
