// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"todolist/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ServeStaticHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/todos",
				Handler: GetTodosHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/todos",
				Handler: CreateTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/todos/:id",
				Handler: GetTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/todos/:id",
				Handler: UpdateTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/todos/:id",
				Handler: DeleteTodoHandler(serverCtx),
			},
		},
	)
}
